name: action workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name : Sample javascript action
        id: hello
        uses: actions/checkout@v3
        with:
          who-to-greet: devopshint

      - name: Get the out put time
        run: echo "${{steps.hello.outputs.time}}"


